### ISSUE TITLE
For CUBE servers on state: present, volume properties parameters such as ssh_keys and user_data not sent to API

### ISSUE THREAD

**Issue by mrndev** [ionos-cloud/module-ansible#114]
## Description
SSH keys are not injected to official Ubuntu IONOS images when deploying CUBEs with Ansible playbooks. It works perfectly for the normal VMs (compute engines) but cubes fail.

## Expected behavior
SSH public key is injected for Cubes just like for the normal VMs

## Environment

Ansible version:
```
ansible [core 2.12.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mnylund/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/mnylund/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```
Module version: 
```
pip3 list|grep ion
Package                   Version
ionoscloud                6.1.0
ionoscloud-dbaas-postgres 1.0.2
```
OS: 
```
 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

## How to Reproduce

Run this play book and then try to ansible ping to both servers. VM works ok, Cube will fail:
```
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    servertpl: &servertpl
      datacenter: MyDatacenter
      image_password: secretpassword
      location: de/txl
      count: 1
      cores: 2
      ram: 2048
      cpu_family: INTEL_SKYLAKE
      volume_size: 200
      image: 5d367080-076a-11ed-b441-96ff36bbb3ad
      state: present
      assign_public_ip: true
      remove_boot_volume: true
      ssh_keys:
      - "{{ lookup('file','~/.ssh/id_rsa.pub') }}"

  tasks:
  - name: Create a Compute Engine VM
    ionoscloudsdk.ionoscloud.server:
      <<: *servertpl
      disk_type: HDD
      name: MyVM

  - name: Create a Cube
    ionoscloudsdk.ionoscloud.server:
      <<: *servertpl
      template_uuid: "7f8dfdb3-594b-4ae2-ae2e-a9dfcbf05f74"
      type: CUBE
      disk_type: DAS
      name: MyCube

```
I checked with the web console that on cube, the ssh public key was not added to /root/.ssh/..

## Error and Debug Output
```
┌─[mnylund][~/learn-ansible]
└─▪ ansible -i hosts -uroot MyDatacenter -mping
MyCube | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '85.215.193.57' (ECDSA) to the list of known hosts.\r\nroot@85.215.193.57: Permission denied (publickey).",
    "unreachable": true
}
MyVM | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
```
