### ISSUE TITLE
k8s_nodepool with lan_ids not working

### ISSUE THREAD

**Issue by attrib** [ionos-cloud/module-ansible#138]
## Description

Trying to run following ansible task

```yaml
    - name: Create k8s cluster nodepool
      ionoscloudsdk.ionoscloud.k8s_nodepool:
        nodepool_name: "DO-DRP01"
        k8s_cluster_id: "{{k8s_cluster_id}}"
        datacenter_id: "{{datacenter_id.stdout}}"
        lan_ids:
          - id: 2
            dhcp: false
        node_count: 1
        cpu_family: "INTEL_SKYLAKE"
        cores_count: "1"
        ram_size: "2048"
        availability_zone: "AUTO"
        storage_type: "HDD"
        storage_size: "30"
```

Returns `fatal: [localhost]: FAILED! => {"changed": false, "msg": "Elements value for option 'lan_ids' is of type <class 'dict'> and we were unable to convert to int: <class 'dict'> cannot be converted to an int"}`

If I just do `lan_ids: 2` I get a more or less expected error from IONOS API:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "failed to create the k8s cluster nodepool: (400)\nReason: Bad Request\nHTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Tue, 08 Nov 2022 15:23:57 GMT', 'Content-Type': 'application/json', 'Content-Length': '393', 'Connection': 'close', 'Access-Control-Allow-Credentials': 'true', 'Vary': 'Origin', 'X-Frame-Options': 'SAMEORIGIN', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': '*', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Methods': '*'})\nHTTP response body: {\n  \"httpStatus\" : 400,\n  \"messages\" : [ {\n    \"errorCode\" : \"304\",\n    \"message\" : \"Failed to parse request body. [line: 1, column: 257] Cannot construct instance of `com.ionos.api.rest.v6.model.pojo.properties.KubernetesNodePoolPropertiesV6$KubernetesLanV6` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (2)\"\n  } ]\n}\n\n"}
```

## Expected behavior

```
lan_ids property should work.
```

## Environment

Ansible version:
```
ansible [core 2.12.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```
Module version: 
```
Ansible ionoscloud 6.4.1
Python ionoscloud 6.1.4               
```
OS: 
```
Debian 11
```
