### ISSUE TITLE
bug: new module version requires additional field creating discrepancy to the docs

### ISSUE THREAD

**Issue by hegerdes** [ionos-cloud/module-ansible#179]
## Description

The new 7.0 Version requires to set the `licence_type` field for additional volumes - despite the docs saying otherwise> This also breaks backwards compatibility. 

## Expected behavior

You do not need a `licence_type` field for additional HDDs and SSDs

## Environment

Ansible version:
```
ansible [core 2.15.3]
  config file = None
  configured module search path = ['/home/henrik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/henrik/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/henrik/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/henrik/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```
Module version: 
```
ionoscloudsdk.ionoscloud:7.0.0-beta.1
```
OS: 
```
RedHat Linux & Windows
```

## Configuration Files

None

## How to Reproduce

Upgrade to the new module version  
Create a Task with an additional volume:
```yml
- name: attach_volumes | Attach additional volumes to server
  ionoscloudsdk.ionoscloud.volume:
    datacenter: "{{ datacenter.id }}"
    server: "{{ provisioned_server.id }}"
    name: "{{ current_vm.name }}-{{ vm_identifier_postfix }}-vol-{{ volume.name }}"
    size: "{{ volume.size | int }}"
    disk_type: "{{ volume.type }}"
    state: "present"
    wait: true
    # Error if this is not present
    # licence_type: 'OTHER'
    wait_timeout: "{{ ionos_timeout }}"
  loop: "{{ [current_vm.volumes }}"
  loop_control:
    loop_var: volume
    index_var: volume_idx
```

## Error and Debug Output

Require field `licence_type` or `image` not set.

## Additional Notes

The [Docs](https://docs.ionos.com/ansible/api/compute-engine/volume#available-parameters-for-state-present) say, that this field is NOT required and it wasn't before. Now either the docs are wrong or the module has a bug.
