### ISSUE TITLE
Speed up user and user_info modules by filtering server-side

### ISSUE THREAD

**Issue by jplitza** [ionos-cloud/module-ansible#203]
### Current SDK Version

```
7.4.1
```

### Use-cases

Each invocation of the user or user_info module seems to always fetch a full list of users from the server. For me, this takes 40 seconds.

### Attempted Solutions

```
- ionoscloudsdk.ionoscloud.user:
    firstname: Jane
    lastname: Doe
    email: doe@example.org
```
And then wait. For a long time. Each time.

### Proposal

Use server-side filtering to only fetch relevant users. Since the email is an identifying key, doing the equivalent of `ionosctl user list -F email=doe@example.org` (which only takes <1s) would suffice for the above invocation.

Also, when using the `filters` attribute for `user_info`, it would also be nice to filter server-side.
