### ISSUE TITLE
Add "SSD Premium"

### ISSUE THREAD

**Issue by arteonprifti** [ionos-cloud/module-ansible#4]
Please add the type "SSD Premium" as a disk_type when adding a volume

https://github.com/ionos-cloud/module-ansible/blob/master/plugins/modules/volume.py

  disk_type:
    description:
      - The disk type of the volume.
    required: false
    default: HDD
    choices: [ "HDD", "SSD" ]

https://devops.ionos.com/api/cloud/v5/#volumes

**Comment by arteonprifti** [comment]
Actually using SSD creates a SSD Premium Volume. Setting the SSD Standard would be much the case here

```
---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
      ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:
    - name: Provision a server
      server:
          datacenter: 	my-test-dc
          location:     de/fra
          availability_zone: ZONE_1
          name: test-name
          count: 1
          cores: 2
          cpu_family: INTEL_SKYLAKE
          ram: 4096
          image: ubuntu:20.04
          disk_type: SSD
          ssh_keys:
            - "{{ ssh_public_key }}"
```
