### ISSUE TITLE
k8s_nodepool with public_ips does not allow repeated run of the playbook

### ISSUE THREAD

**Issue by rdxmb** [ionos-cloud/module-ansible#44]
## Description

When a `k8s_nodepool` has `public_ips` defined, the task can only be run once without errors (using  `state: present` )

On its second run there is an error:

```
TASK [k8s cluster with fixed ips] ********************************************************************************************************************************************************************************
fatal: [dc9]: FAILED! => {"changed": false, "msg": "failed to create the k8s cluster nodepool: (422)\nReason: Unprocessable Entity\nHTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Tue, 01 Feb 2022 09:52:12 GMT', 'Content-Type': 'application/json', 'Content-Length': '543', 'Connection': 'close', 'X-Frame-Options': 'SAMEORIGIN', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': '*', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Allow-Credentials': 'true'})\nHTTP response body: {\n  \"httpStatus\" : 422,\n  \"messages\" : [ {\n    \"errorCode\" : \"410\",\n    \"message\" : \"[(root).properties.publicIps] '85.215.215.143' is in use by other resource\"\n  }, {\n    \"errorCode\" : \"410\",\n    \"message\" : \"[(root).properties.publicIps] '85.215.211.103' is in use by other resource\"\n  }, {\n    \"errorCode\" : \"410\",\n    \"message\" : \"[(root).properties.publicIps] '85.215.211.59' is in use by other resource\"\n  }, {\n    \"errorCode\" : \"410\",\n    \"message\" : \"[(root).properties.publicIps] '85.215.213.230' is in use by other resource\"\n  } ]\n}\n\n"}
```

## Expected behavior

The task can be run multiple times without changing anything (`state=ok`) and without errors.

(When creating a nodepool without defined `public_ips`, multiple re-runs are supported)

## Environment

Ansible version:
```
$ ansible-playbook --version
ansible-playbook [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/marc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/marc/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/marc/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/marc/.local/bin/ansible-playbook
  python version = 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```
Module version: 
```
$ ansible-galaxy collection list | grep ionos
ionoscloudsdk.ionoscloud 6.1.0
```

```
$ pip list | grep ionos
ionoscloud             6.0.0
```

OS: 
```
Kbuntu 21.10
```

## Configuration Files
```
[defaults]
host_key_checking = False
timeout = 50 
ansible_managed = '## Do not edit on server - for this will be overwritten by ansible provisioning'
[ssh_connection]
ssh_args = -o ForwardAgent=yes
[default]
library = //module-ansible/plugins/modules
```

## How to Reproduce
- Define an ipblock
- Use its ips as `public_ips` in a `k8s_nodepool`-task with `state: present`
- Run the playbook with this task twice. The first run will be successfull. The second run will result the error posted above.

### playbook tasks

```
# ------------ dynamic ips following -------------------------

- name: k8s cluster with dynamic ips - this can be run multiple times without problems
  k8s_nodepool:
    nodepool_name: "pool-with-dynamic-ips"
    node_count: "2"
    cores_count: "1"
    ram_size: "2048"
    storage_type: "HDD"
    storage_size: "20"
    k8s_cluster_id: "{{ k8s_cluster_response.cluster.id }}"
    datacenter_id: "{{ datacenter_response.datacenter.id }}"
    availability_zone: "AUTO"
    cpu_family: "INTEL_SKYLAKE"
    k8s_version: "1.20.10"
    state: present

# ------------ fixed ips following -------------------------

- name: reserve ipblock - this can be run multiple times without problems
  ipblock:
    name: "k8s-nodepool-frankfurt"
    location: "de/fra"
    size: "3"
    state: present
  register: ipblock_response

- name: k8s cluster with fixed ips - this can only be run once
  k8s_nodepool:
    nodepool_name: "pool-with-fixed-ips"
    node_count: "2"
    cores_count: "1"
    ram_size: "2048"
    storage_type: "HDD"
    storage_size: "20"
    k8s_cluster_id: "{{ k8s_cluster_response.cluster.id }}"
    datacenter_id: "{{ datacenter_response.datacenter.id }}"
    availability_zone: "AUTO"
    cpu_family: "INTEL_SKYLAKE"
    k8s_version: "1.20.10"
    public_ips: "{{ ipblock_response.ipblock.properties.ips }}"
    state: present
```

**Comment by rdxmb** [comment]
Here is my workaround:

```
- name: workaround - check for existing nodepool
  raw: "ionosctl k8s nodepool list --cluster-id={{ k8s_cluster_response.cluster.id }} --filters name={{ item.name }} -o json | jq -r .Resources[].id"
  register: nodepool_check_response

- name: k8s nodepool with fixed ips (update)
  k8s_nodepool:
    nodepool_id: "{{ nodepool_check_response.stdout_lines[0] }}"
    node_count: "{{ item.node_count }}"
    cores_count: "{{ item.cores_count }}"
    ram_size: "{{ item.ram_size }}"
    storage_type: "{{ item.storage_type | upper }}"
    storage_size: "{{ item.storage_size }}"
    k8s_cluster_id: "{{ k8s_cluster_response.cluster.id }}"
    datacenter_id: "{{ datacenter_response.datacenter.id }}"
    availability_zone: "{{ item.zone }}"
    cpu_family: "INTEL_SKYLAKE"
    k8s_version: "{{ item.k8s_version }}"
    public_ips: "{{ ipblock_response.ipblock.properties.ips }}"
    state: update
  when: item.ip_type == "fixed" and nodepool_check_response.stdout_lines | length == 1

- name: k8s nodepool with fixed ips (create)
  k8s_nodepool:
    nodepool_name: "{{ item.name }}"
    node_count: "{{ item.node_count }}"
    cores_count: "{{ item.cores_count }}"
    ram_size: "{{ item.ram_size }}"
    storage_type: "{{ item.storage_type | upper }}"
    storage_size: "{{ item.storage_size }}"
    k8s_cluster_id: "{{ k8s_cluster_response.cluster.id }}"
    datacenter_id: "{{ datacenter_response.datacenter.id }}"
    availability_zone: "{{ item.zone }}"
    cpu_family: "INTEL_SKYLAKE"
    k8s_version: "{{ item.k8s_version }}"
    public_ips: "{{ ipblock_response.ipblock.properties.ips }}"
    state: present
  when: item.ip_type == "fixed" and nodepool_check_response.stdout_lines | length == 0
```
