### ISSUE TITLE
running declarative tasks with ip_block of k8s_nodepool not supported

### ISSUE THREAD

**Issue by rdxmb** [ionos-cloud/module-ansible#54]
## Description

When running a task with `k8s_nodepool` or `ip_block` it is not possible to do that in a declarative way, as the tasks behave in an inconsequent way to create/update/ignore changes. 

1. As the author of the playbook has to differenciate if the task is running with `state: present` or `state: update`, the same play(book) cannot run again just to create **or** update the nodepool as it is defined in the task.

2. When creating a nodepool with `state: present`, the `nodepool_name` is mandatory. When running this task again, **a second nodepool with the same name but other id is created.**

3. When running a task with `ipblock` and `state: present` twice, **nothing is done**. That's ok. But: If I change the `size`, for example, the state is also `ok` and the block is not resized.

4. When updating a nodepool with `state: update`, the `nodepool_id` is mandatory. So this task cannot be used to **create** a nodepool.

So running a task with `ipblock` or `k8s_nodepool` twice is not kind of simple and workarounds are needed.

## Expected behavior

Like other definitions (e.g. `ipblock`), it is possible to run tasks again - this is part of the declarative thinking and provisioning. If nothing has changed in the play, the task ends with `<ok>`.

This is also the ansible idea:
> 
Ansible Playbooks offer a repeatable, re-usable, simple configuration management and multi-machine deployment system, one that is well suited to deploying complex applications.

https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html

## Additional Notes

Actually, I have built a workaround for that when running `k8s_nodepool`

It seems that I also have to do that for `ipblock`, as the block actually is not resized when changing the `size`, running it with `present`.

```
- name: "reserve ipblock {{ inventory_hostname }}-{{ item.name }}"
  ipblock:
    name: "{{ inventory_hostname }} | nodePool-{{ item.name }}"
    location: "{{ item.location }}"
    size: "{{ item.auto_scaling.max_node_count + 1 }}"
    state: present
  when: item.ip_type == "fixed"
  register: ipblock_response

- name: workaround - check for existing nodepool
  raw: "ionosctl k8s nodepool list --cluster-id={{ k8s_cluster_response.cluster.id }} --filters name={{ inventory_hostname }}-{{ item.name }} -o json | jq -r .Resources[].id"
  register: nodepool_check_response

- name: k8s nodepool with fixed ips (create)
  k8s_nodepool:
    nodepool_name: "{{ inventory_hostname }}-{{ item.name }}"
    node_count: "{{ item.node_count }}"
    cores_count: "{{ item.cores_count }}"
    ram_size: "{{ item.ram_size }}"
    storage_type: "{{ item.storage_type | upper }}"
    storage_size: "{{ item.storage_size }}"
    k8s_cluster_id: "{{ k8s_cluster_response.cluster.id }}"
    datacenter_id: "{{ datacenter_response.datacenter.id }}"
    availability_zone: "{{ item.zone }}"
    cpu_family: "INTEL_SKYLAKE"
    k8s_version: "{{ item.k8s_version }}"
    public_ips: "{{ ipblock_response.ipblock.properties.ips }}"
    state: present
    labels:
      ip-type: fixed
  when: item.ip_type == "fixed" and nodepool_check_response.stdout_lines | length == 0

- name: k8s nodepool with fixed ips (update)
  k8s_nodepool:
    nodepool_id: "{{ nodepool_check_response.stdout_lines[0] }}"
    node_count: "{{ item.node_count }}"
    cores_count: "{{ item.cores_count }}"
    ram_size: "{{ item.ram_size }}"
    storage_type: "{{ item.storage_type | upper }}"
    storage_size: "{{ item.storage_size }}"
    k8s_cluster_id: "{{ k8s_cluster_response.cluster.id }}"
    datacenter_id: "{{ datacenter_response.datacenter.id }}"
    availability_zone: "{{ item.zone }}"
    cpu_family: "INTEL_SKYLAKE"
    k8s_version: "{{ item.k8s_version }}"
    public_ips: "{{ ipblock_response.ipblock.properties.ips }}"
    state: update
    labels:
      ip-type: fixed
  when: item.ip_type == "fixed" and nodepool_check_response.stdout_lines | length == 1
```

**Comment by rdxmb** [comment]
for having a declarative definition to add **or** edit `k8s_cluster`s my workaround now looks like this:

```
    - name: Create k8s cluster
      ionoscloudsdk.ionoscloud.k8s_cluster:
        cluster_name: "{{ inventory_hostname }}"        
        state: present
      register: k8s_cluster_response
    - name: Edit k8s cluster
      ionoscloudsdk.ionoscloud.k8s_cluster:
        cluster_name: "{{ inventory_hostname }}"
        k8s_cluster_id: "{{ k8s_cluster_response.cluster.id }}"
        maintenance_window: "{{ k8s.maintenance_window }}"
        k8s_version: "{{ k8s.k8s_version }}"
        api_subnet_allow_list: "83.135.39.98/32,93.235.156.28/32,79.208.255.10/32"
        state: update
```
