### ISSUE TITLE
k8s_nodepool needs cpu_family for creation

### ISSUE THREAD

**Issue by rdxmb** [ionos-cloud/module-ansible#58]
## Description

the `cpu_familiy` is needed for creation.

## Expected behavior

according to the docs, the cpu_familiy is not needed for creation.

## Additional Notes
```

error output:

TASK [k8s nodepool with dynamic ips (create)] **********************************
fatal: [k09]: FAILED! => {"changed": false, "msg": "cpu_family parameter is required updating a k8s nodepool"}
```

playbook:

```
- name: create datacenter
  ionoscloudsdk.ionoscloud.datacenter:
    name: "{{ inventory_hostname }} | {{ item.location | lower }}"
    location: "{{ item.location | lower }}"
    wait: true
  register: datacenter_response

- name: check for dependency - ionosctl binary
  raw: "ionosctl --help > /dev/null"

- name: workaround - check for existing nodepool
  raw: "ionosctl k8s nodepool list --cluster-id={{ k8s_cluster_response.cluster.id }} --filters name={{ inventory_hostname }}-{{ item.name }} -o json | jq -r .Resources[].id"
  register: nodepool_check_response

- name: k8s nodepool with dynamic ips (create)
  ionoscloudsdk.ionoscloud.k8s_nodepool:
    nodepool_name: "{{ inventory_hostname }}-{{ item.name }}"
    k8s_cluster_id: "{{ k8s_cluster_response.cluster.id }}"
    datacenter_id: "{{ datacenter_response.datacenter.id }}"
    node_count: "{{ item.node_count }}"
    cores_count: "{{ item.cores_count }}"
    ram_size: "{{ item.ram_size }}"
    availability_zone: "{{ item.zone }}"
    storage_type: "{{ item.storage_type | upper }}"
    storage_size: "{{ item.storage_size }}"
    wait: true
    state: present
  when: nodepool_check_response.stdout_lines | length == 0

- name: k8s nodepool with dynamic ips (update)
  ionoscloudsdk.ionoscloud.k8s_nodepool:
    k8s_cluster_id: "{{ k8s_cluster_response.cluster.id }}"
    nodepool_id: "{{ nodepool_check_response.stdout_lines[0] }}"
    node_count: "{{ item.node_count }}"
    k8s_version: "{{ item.k8s_version }}"
    availability_zone: "{{ item.zone }}"    
    cpu_family: "INTEL_SKYLAKE"
    auto_scaling:
      min_node_count: "{{ item.auto_scaling.min_node_count }}"
      max_node_count: "{{ item.auto_scaling.max_node_count }}"
    labels:
      reddoxx/ip-type: dynamic
    wait: true
    state: update
  when: nodepool_check_response.stdout_lines | length == 1
```
