### ISSUE TITLE
manage ressources of a group

### ISSUE THREAD

**Issue by genofire** [ionos-cloud/module-ansible#94]
### Current SDK Version

```
...
```

### Use-cases

Add a vdc to ressources of a group (by name or uuid).

**Comment by avirtopeanu-ionos** [comment]
Hello @genofire, what SDK version are you using?

If you would like to add resources to groups, you can use shares. Here is the relevant official IONOS documentation: https://docs.ionos.com/ansible/api/user-management/share

In your case, add this to your playbook

```
- name: Create share
    share:
      group: Group Name
      edit_privilege: true
      share_privilege: true
      resource_ids:
        - vdc_id_here
      state: present
```

Is this what you are looking for?
